### ISSUE TITLE
bootstrap crashes with java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by jyio** [jyio/botbrew-gui#22]
The bootstrap process crashes on some devices, generating the following stack trace:

```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
    at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1299)
    at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1310)
    at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:541)
    at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:525)
    at android.support.v4.app.DialogFragment.show(DialogFragment.java:123)
    at com.botbrew.basil.BootstrapActivity.showInstall(BootstrapActivity.java:345)
    at com.botbrew.basil.BootstrapActivity$DownloadDialogFragment$2.onPostExecute(BootstrapActivity.java:101)
    at com.botbrew.basil.BootstrapActivity$DownloadDialogFragment$2.onPostExecute(BootstrapActivity.java:1)
    at android.os.AsyncTask.finish(AsyncTask.java:602)
    at android.os.AsyncTask.access$600(AsyncTask.java:156)
    at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:615)
    at android.os.Handler.dispatchMessage(Handler.java:99)
    at android.os.Looper.loop(Looper.java:137)
    at android.app.ActivityThread.main(ActivityThread.java:4575)
    at java.lang.reflect.Method.invokeNative(Native Method)
    at java.lang.reflect.Method.invoke(Method.java:511)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:556)
    at dalvik.system.NativeStart.main(Native Method)
```

Affected devices include:
- Android 4.0.4
  - Samsung SGH-T989
  - Samsung Galaxy Nexus
  - Samsung Galaxy S
  - Samsung GT-I9100
  - HP Touchpad
- Android 4.0.3
  - Samsung GT-I9100
- Android 2.3.7
  - Motorola Droid
- Android 2.3.3
  - Samsung GT-I9000B
  - HTC Desire HD
- Android 2.2.1
  - LG Optimus M

**Comment by jyio** [comment]
This happens when one calls the launcher (or any other app) to the foreground while bootstrapping. For some reason, I was unable to reproduce it for a while, but a fix is on the way.
